import time
from pages.personal_page import*
from pages.authorization_page import AutoPage
import json


def test_friends_button(driver):
    friends_page = FriendsPage(driver)
    friends_page.visit()
    auto_page = AutoPage(driver)
    auto_page.visit()
    auto_page.all_fields_load()
    auto_page.login_field_send_value("+79165390160")
    auto_page.password_field_send_value("Ych2508")
    time.sleep(2)
    auto_page.btn_enter.click()
    time.sleep(7)
    friends_page.friends_button_load()
    friends_page.friends_button_click()
    time.sleep(5)
    assert friends_page.friends_page_open().is_displayed()


def test_photo_button(driver):
    foto_page = PhotoPage(driver)
    foto_page.visit()
    auto_page = AutoPage(driver)
    auto_page.visit()
    auto_page.all_fields_load()
    auto_page.login_field_send_value("+79165390160")
    auto_page.password_field_send_value("Ych2508")
    time.sleep(2)
    auto_page.btn_enter.click()
    time.sleep(7)
    foto_page.photo_button_load()
    foto_page.photo_button_click()
    time.sleep(5)
    assert foto_page.photo_page_open().is_displayed()


def test_music_button(driver):
    msc_page = MusicPage(driver)
    msc_page.visit()
    auto_page = AutoPage(driver)
    auto_page.visit()
    auto_page.all_fields_load()
    auto_page.login_field_send_value("+79165390160")
    auto_page.password_field_send_value("Ych2508")
    time.sleep(2)
    auto_page.btn_enter.click()
    time.sleep(7)
    msc_page.music_button_load()
    msc_page.music_button_click()
    time.sleep(5)
    assert msc_page.music_page_open().is_displayed()


def test_video_button(driver):
    vdo_page = VideoPage(driver)
    vdo_page.visit()
    auto_page = AutoPage(driver)
    auto_page.visit()
    auto_page.all_fields_load()
    auto_page.login_field_send_value("+79165390160")
    auto_page.password_field_send_value("Ych2508")
    time.sleep(2)
    auto_page.btn_enter.click()
    time.sleep(7)
    vdo_page.video_button_load()
    vdo_page.video_button_click()
    time.sleep(5)
    assert vdo_page.video_page_open().is_displayed()


def test_my_games_button(driver):
    gms_page = GamesPage(driver)
    gms_page.visit()
    auto_page = AutoPage(driver)
    auto_page.visit()
    auto_page.all_fields_load()
    auto_page.login_field_send_value("+79165390160")
    auto_page.password_field_send_value("Ych2508")
    time.sleep(2)
    auto_page.btn_enter.click()
    time.sleep(7)
    gms_page.games_button_load()
    gms_page.games_button_click()
    time.sleep(5)
    assert gms_page.games_page_open().is_displayed()


def test_ad_button(driver):
    ad_page = AdvertismentPage(driver)
    ad_page.visit()
    auto_page = AutoPage(driver)
    auto_page.visit()
    auto_page.all_fields_load()
    auto_page.login_field_send_value("+79165390160")
    auto_page.password_field_send_value("Ych2508")
    time.sleep(2)
    auto_page.btn_enter.click()
    time.sleep(7)
    ad_page.ad_button_load()
    ad_page.ad_button_click()
    time.sleep(5)
    assert ad_page.ad_page_open().is_displayed()


def test_mini_apps_button(driver):
    ma_page = MiniAppsPage(driver)
    ma_page.visit()
    auto_page = AutoPage(driver)
    auto_page.visit()
    auto_page.all_fields_load()
    auto_page.login_field_send_value("+79165390160")
    auto_page.password_field_send_value("Ych2508")
    time.sleep(2)
    auto_page.btn_enter.click()
    time.sleep(7)
    ma_page.mini_apps_button_load()
    ma_page.mini_apps_button_click()
    time.sleep(5)
    assert ma_page.mini_apps_page_open().is_displayed()


def test_my_page_button(driver):
    my_page = MyPage(driver)
    my_page.visit()
    auto_page = AutoPage(driver)
    auto_page.visit()
    auto_page.all_fields_load()
    auto_page.login_field_send_value("+79165390160")
    auto_page.password_field_send_value("Ych2508")
    time.sleep(2)
    auto_page.btn_enter.click()
    time.sleep(7)
    my_page.my_page_button_load()
    my_page.my_page_button_click()
    time.sleep(5)
    assert my_page.my_page_open().is_displayed()


def test_manage_button(driver):
    mng_page = ManagePage(driver)
    mng_page.visit()
    auto_page = AutoPage(driver)
    auto_page.visit()
    auto_page.all_fields_load()
    auto_page.login_field_send_value("+79165390160")
    auto_page.password_field_send_value("Ych2508")
    time.sleep(2)
    auto_page.btn_enter.click()
    time.sleep(7)
    mng_page.manage_button_load()
    mng_page.manage_button_click()
    time.sleep(5)
    assert mng_page.manage_page_open().is_displayed()


def test_calls_button(driver):
    cls_page = CallsPage(driver)
    cls_page.visit()
    auto_page = AutoPage(driver)
    auto_page.visit()
    auto_page.all_fields_load()
    auto_page.login_field_send_value("+79165390160")
    auto_page.password_field_send_value("Ych2508")
    time.sleep(2)
    auto_page.btn_enter.click()
    time.sleep(7)
    cls_page.calls_button_load()
    cls_page.calls_button_click()
    time.sleep(5)
    assert cls_page.calls_page_open().is_displayed()


def test_messengers_button(driver):
    msn_page = MessengersPage(driver)
    msn_page.visit()
    auto_page = AutoPage(driver)
    auto_page.visit()
    auto_page.all_fields_load()
    auto_page.login_field_send_value("+79165390160")
    auto_page.password_field_send_value("Ych2508")
    time.sleep(2)
    auto_page.btn_enter.click()
    time.sleep(7)
    msn_page.messengers_button_load()
    msn_page.messengers_button_click()
    time.sleep(5)
    assert msn_page.messengers_page_open().is_displayed()


def test_news_button(driver):
    nws_page = NewsPage(driver)
    nws_page.visit()
    auto_page = AutoPage(driver)
    auto_page.visit()
    auto_page.all_fields_load()
    auto_page.login_field_send_value("+79165390160")
    auto_page.password_field_send_value("Ych2508")
    time.sleep(2)
    auto_page.btn_enter.click()
    time.sleep(7)
    nws_page.news_button_load()
    nws_page.news_button_click()
    time.sleep(5)
    assert nws_page.news_page_open().is_displayed()


def test_podcasts_button(driver):
    pdc_page = PodcastsPage(driver)
    pdc_page.visit()
    auto_page = AutoPage(driver)
    auto_page.visit()
    auto_page.all_fields_load()
    auto_page.login_field_send_value("+79165390160")
    auto_page.password_field_send_value("Ych2508")
    time.sleep(2)
    auto_page.btn_enter.click()
    time.sleep(7)
    pdc_page.podcasts_button_load()
    pdc_page.podcasts_button_click()
    time.sleep(5)
    assert pdc_page.podcasts_page_open().is_displayed()


def test_coronavirus_button(driver):
    crv_page = CoronaVirusPage(driver)
    crv_page.visit()
    auto_page = AutoPage(driver)
    auto_page.visit()
    auto_page.all_fields_load()
    auto_page.login_field_send_value("+79165390160")
    auto_page.password_field_send_value("Ych2508")
    time.sleep(2)
    auto_page.btn_enter.click()
    time.sleep(7)
    crv_page.coronavirus_button_load()
    crv_page.coronavirus_button_click()
    time.sleep(5)
    assert crv_page.coronavirus_page_open().is_displayed()


def test_football_button(driver):
    ftb_page = FootballPage(driver)
    ftb_page.visit()
    auto_page = AutoPage(driver)
    auto_page.visit()
    auto_page.all_fields_load()
    auto_page.login_field_send_value("+79165390160")
    auto_page.password_field_send_value("Ych2508")
    time.sleep(2)
    auto_page.btn_enter.click()
    time.sleep(7)
    ftb_page.football_button_load()
    ftb_page.football_button_click()
    time.sleep(5)
    assert ftb_page.football_page_open().is_displayed()


def test_recommendations_button(driver):
    rcm_page = RecommendationsPage(driver)
    rcm_page.visit()
    auto_page = AutoPage(driver)
    auto_page.visit()
    auto_page.all_fields_load()
    auto_page.login_field_send_value("+79165390160")
    auto_page.password_field_send_value("Ych2508")
    time.sleep(2)
    auto_page.btn_enter.click()
    time.sleep(7)
    rcm_page.recommendations_button_load()
    rcm_page.recommendations_button_click()
    time.sleep(5)
    assert rcm_page.recommendations_page_open().is_displayed()


def test_search_personal_button(driver):
    srp_page = SearchPersonalPage(driver)
    srp_page.visit()
    auto_page = AutoPage(driver)
    auto_page.visit()
    auto_page.all_fields_load()
    auto_page.login_field_send_value("+79165390160")
    auto_page.password_field_send_value("Ych2508")
    time.sleep(2)
    auto_page.btn_enter.click()
    time.sleep(7)
    srp_page.search_personal_button_load()
    srp_page.search_personal_button_click()
    time.sleep(5)
    assert srp_page.search_personal_page_open().is_displayed()


def test_reactions_button(driver):
    rcs_page = ReactionsPage(driver)
    rcs_page.visit()
    auto_page = AutoPage(driver)
    auto_page.visit()
    auto_page.all_fields_load()
    auto_page.login_field_send_value("+79165390160")
    auto_page.password_field_send_value("Ych2508")
    time.sleep(2)
    auto_page.btn_enter.click()
    time.sleep(7)
    rcs_page.reactions_button_load()
    rcs_page.reactions_button_click()
    time.sleep(5)
    assert rcs_page.reactions_page_open().is_displayed()


def test_updates_button(driver):
    upd_page = UpdatesPage(driver)
    upd_page.visit()
    auto_page = AutoPage(driver)
    auto_page.visit()
    auto_page.all_fields_load()
    auto_page.login_field_send_value("+79165390160")
    auto_page.password_field_send_value("Ych2508")
    time.sleep(2)
    auto_page.btn_enter.click()
    time.sleep(7)
    upd_page.updates_button_load()
    upd_page.updates_button_click()
    time.sleep(5)
    assert upd_page.updates_page_open().is_displayed()


def test_comments_button(driver):
    cmt_page = CommentsPage(driver)
    cmt_page.visit()
    auto_page = AutoPage(driver)
    auto_page.visit()
    auto_page.all_fields_load()
    auto_page.login_field_send_value("+79165390160")
    auto_page.password_field_send_value("Ych2508")
    time.sleep(2)
    auto_page.btn_enter.click()
    time.sleep(7)
    cmt_page.comments_button_load()
    cmt_page.comments_button_click()
    time.sleep(5)
    assert cmt_page.comments_page_open().is_displayed()


def test_manage_button(driver):
    mng_page = ManagePage(driver)
    mng_page.visit()
    auto_page = AutoPage(driver)
    auto_page.visit()
    auto_page.all_fields_load()
    auto_page.login_field_send_value("+79165390160")
    auto_page.password_field_send_value("Ych2508")
    time.sleep(2)
    auto_page.btn_enter.click()
    time.sleep(7)
    mng_page.manage_button_load()
    mng_page.manage_button_click()
    time.sleep(5)
    assert mng_page.manage_page_open().is_displayed()




